SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
CREATE DATABASE IF NOT EXISTS `mnrao` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE `mnrao`;
COMMIT;